# Generated by Django 3.2.23 on 2024-02-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tijianorder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tijianorder',
            table='tb_tj_order',
        ),
    ]
