# Generated by Django 3.2.23 on 2024-02-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tijianorder_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TijianOrder',
        ),
    ]
