# Generated by Django 3.2.23 on 2024-02-15 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_tijianorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TijianOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkupTypee', models.CharField(max_length=40, verbose_name='预约类型')),
                ('ordertime', models.CharField(max_length=40, verbose_name='预约时间')),
                ('ordertip', models.CharField(max_length=100, verbose_name='预约信息')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '体检预约',
                'verbose_name_plural': '体检预约',
                'db_table': 'tb_tj_order',
            },
        ),
    ]
