# Generated by Django 3.2.23 on 2024-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240330_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='tijian',
            name='blood_oxygen',
            field=models.CharField(default='无数据', max_length=15, verbose_name='血氧饱和度'),
        ),
        migrations.AddField(
            model_name='tijian',
            name='blood_pressure',
            field=models.CharField(default='无数据', max_length=15, verbose_name='血压'),
        ),
        migrations.AddField(
            model_name='tijian',
            name='heart_rate',
            field=models.CharField(default='无数据', max_length=15, verbose_name='心率'),
        ),
    ]
