# Generated by Django 3.2.23 on 2024-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240330_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tijianorder',
            old_name='checkupTypee',
            new_name='checkupType',
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True, verbose_name='额外信息'),
        ),
    ]
