# Generated by Django 3.2.23 on 2024-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240409_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='tijianorder',
            name='bloodTest',
            field=models.BooleanField(default=False, verbose_name='血液检查'),
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='totalPrice',
            field=models.IntegerField(default=0, verbose_name='总价格'),
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='urineTest',
            field=models.BooleanField(default=False, verbose_name='尿液检查'),
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='xRay',
            field=models.BooleanField(default=False, verbose_name='X光'),
        ),
    ]
