# Generated by Django 3.2.23 on 2024-04-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_tijianorder_ordertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tijianorder',
            name='institution',
            field=models.CharField(default=0, max_length=50, verbose_name='到访机构'),
        ),
    ]
