# Generated by Django 3.2.23 on 2024-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240512_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergy_history',
            field=models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, verbose_name='过敏史'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_genetic_disease_history',
            field=models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, verbose_name='家族遗传病史'),
        ),
    ]
