# Generated by Django 3.2.23 on 2024-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20240512_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tijianorder',
            name='ordertime',
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='orderDate',
            field=models.DateField(null=True, verbose_name='预约日期'),
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='orderTime',
            field=models.TimeField(null=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergy_history',
            field=models.CharField(default='无', max_length=100, verbose_name='过敏史'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_genetic_disease_history',
            field=models.CharField(default='无', max_length=100, verbose_name='家族遗传病史'),
        ),
    ]
