# Generated by Django 3.2.23 on 2024-05-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20240515_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tijianorder',
            name='allergy',
            field=models.CharField(default='无', max_length=10, null=True, verbose_name='过敏史'),
        ),
        migrations.AlterField(
            model_name='tijianorder',
            name='familyHistory',
            field=models.CharField(default='无', max_length=10, null=True, verbose_name='家族遗传病史'),
        ),
    ]
