# Generated by Django 3.2.23 on 2024-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20240515_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tijianorder',
            name='allergy_history',
        ),
        migrations.AddField(
            model_name='tijianorder',
            name='allergy',
            field=models.CharField(default='无', max_length=10, null=True, verbose_name='过敏史'),
        ),
        migrations.AlterField(
            model_name='tijianorder',
            name='familyHistory',
            field=models.CharField(default='无', max_length=10, null=True, verbose_name='家族遗传病史'),
        ),
    ]
