# Generated by Django 3.2.23 on 2024-05-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20240515_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergy_history',
            field=models.CharField(default='0', max_length=100, verbose_name='过敏史'),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_genetic_disease_history',
            field=models.CharField(default='0', max_length=100, verbose_name='家族遗传病史'),
        ),
    ]
