# Generated by Django 3.2.23 on 2024-02-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_auto_20240130_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'tb_article_category',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('introd', models.CharField(max_length=50, verbose_name='文章简介')),
                ('content', models.CharField(max_length=800, verbose_name='文章内容')),
                ('release_data', models.DateField(verbose_name='发布日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article_category', verbose_name='所属类型')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorinfo', verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_article',
            },
        ),
    ]
