# Generated by Django 3.2.23 on 2024-02-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=2000, verbose_name='文章内容'),
        ),
    ]
