# Generated by Django 3.2.23 on 2024-04-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='文章内容'),
        ),
    ]
