# Generated by Django 3.2.23 on 2024-01-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=10, verbose_name='科室名称')),
                ('department_area', models.CharField(max_length=10, null=True, verbose_name='科室地址')),
                ('department_introduce', models.CharField(max_length=30, null=True, verbose_name='科室简介')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='医生用户名')),
                ('doctorname', models.CharField(max_length=20, verbose_name='医生真名')),
                ('password', models.CharField(max_length=20, verbose_name='医生账号密码')),
                ('introducation', models.CharField(max_length=200, verbose_name='医生资料')),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='media/doctor_images/', verbose_name='医生图片')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
                'db_table': 'tb_doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertime', models.CharField(max_length=40, verbose_name='预约时间')),
                ('ordertip', models.CharField(max_length=100, verbose_name='预约信息')),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorinfo', verbose_name='预约医生')),
            ],
        ),
    ]
