# Generated by Django 3.2.23 on 2024-01-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='which_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.department', verbose_name='所属科室'),
        ),
    ]
