# Generated by Django 3.2.23 on 2024-01-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctororder',
            options={'verbose_name': '医生预约', 'verbose_name_plural': '医生预约'},
        ),
        migrations.AlterModelTable(
            name='doctororder',
            table='tb_doctor_order',
        ),
    ]
