# Generated by Django 3.2.23 on 2024-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20240330_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='mobile_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
