# Generated by Django 3.2.23 on 2024-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctororder_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='审核状态'),
        ),
    ]
