# Generated by Django 3.2.23 on 2024-04-17 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0006_doctororder_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateTimeField()),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('body_temperature', models.CharField(blank=True, max_length=50, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=50, null=True)),
                ('body_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('body_height', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_oxygen', models.CharField(blank=True, max_length=50, null=True)),
                ('no_symptoms', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('chest_pain', models.BooleanField(default=False)),
                ('abdominal_pain', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('other_symptoms', models.TextField(blank=True, null=True)),
                ('balanced_diet', models.BooleanField(default=False)),
                ('unbalanced_diet', models.BooleanField(default=False)),
                ('good_sleep_quality', models.BooleanField(default=False)),
                ('poor_sleep_quality', models.BooleanField(default=False)),
                ('sufficient_exercise_duration', models.BooleanField(default=False)),
                ('lack_of_exercise', models.BooleanField(default=False)),
                ('no_anxiety', models.BooleanField(default=False)),
                ('anxiety', models.BooleanField(default=False)),
                ('no_medication', models.BooleanField(default=False)),
                ('medication', models.BooleanField(default=False)),
                ('medication_details', models.TextField(blank=True, null=True)),
                ('no_other_physical_conditions', models.BooleanField(default=False)),
                ('other_physical_conditions', models.BooleanField(default=False)),
                ('other_physical_conditions_details', models.TextField(blank=True, null=True)),
                ('doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorinfo', verbose_name='预约医生')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户')),
            ],
            options={
                'verbose_name': '在线问诊',
                'verbose_name_plural': '在线问诊',
                'db_table': 'tb_doctor_ask',
            },
        ),
    ]
