# Generated by Django 3.2.23 on 2024-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20240418_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='doctor_title',
            field=models.CharField(choices=[('住院医师', '住院医师'), ('主治医师', '主治医师'), ('副主任医师', '副主任医师'), ('主任医师', '主任医师')], max_length=20, null=True, verbose_name='医生职称'),
        ),
    ]
