# Generated by Django 3.2.23 on 2024-05-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20240515_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='咨询费用'),
        ),
    ]
